#!/usr/bin/env python3
"""
Multi-seed evaluation summary figures for the temperature case study.

Uses: runs/multiseed_eval_summary.json
      (generated by run_multiseed_eval.sh)

Produces:
  fig_multiseed_all_algos_viol.pdf/.png   — mean±std violation rate, all algos
  fig_multiseed_all_algos_reward.pdf/.png — mean±std reward, all algos
  fig_multiseed_reward_vs_viol.pdf/.png   — scatter: all seeds, reward vs viol
  fig_multiseed_cost_vs_viol.pdf/.png     — scatter: all seeds, cost vs viol
  fig_multiseed_seed_dots.pdf/.png        — per-seed dot plot (violation rate)
"""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.ticker as mticker
import numpy as np

# ---------------------------------------------------------------------------
# IEEE style
# ---------------------------------------------------------------------------
plt.rcParams.update({
    "font.family": "serif",
    "font.serif": ["Times New Roman", "DejaVu Serif", "Liberation Serif"],
    "font.size": 8,
    "axes.titlesize": 9,
    "axes.labelsize": 8,
    "xtick.labelsize": 7,
    "ytick.labelsize": 7,
    "legend.fontsize": 6.5,
    "figure.dpi": 300,
    "savefig.dpi": 300,
    "savefig.bbox": "tight",
    "savefig.pad_inches": 0.03,
    "axes.grid": True,
    "grid.alpha": 0.20,
    "grid.linewidth": 0.3,
    "grid.linestyle": "--",
    "axes.linewidth": 0.5,
    "lines.linewidth": 1.0,
    "lines.markersize": 3.5,
    "legend.framealpha": 0.92,
    "legend.edgecolor": "0.8",
    "legend.fancybox": False,
    "text.usetex": False,
    "xtick.major.width": 0.4,
    "ytick.major.width": 0.4,
    "xtick.major.size": 3,
    "ytick.major.size": 3,
    "xtick.direction": "in",
    "ytick.direction": "in",
})

COL1 = 3.5
COL2 = 7.16

BASE = Path("/home/extra-storage/THESIS/Safe-CityLearn-Fork/Safe-CityLearn-Fork")
FIG_DIR = BASE / "docs" / "temperature_case_study" / "figures"
FIG_DIR.mkdir(parents=True, exist_ok=True)
SUMMARY_JSON = BASE / "runs" / "multiseed_eval_summary.json"

# ---------------------------------------------------------------------------
# Colors / markers
# ---------------------------------------------------------------------------
ALGO_COLORS = {
    "CSAC-LB": "#c0392b",
    "CPO":     "#2471a3",
    "SAC-Lag": "#795548",
    "CUP":     "#e67e22",
    "FOCOPS":  "#27ae60",
}
ALGO_MARKERS = {
    "CSAC-LB": "o",
    "CPO":     "s",
    "SAC-Lag": "P",
    "CUP":     "^",
    "FOCOPS":  "D",
}
# Display order for bars (best safety first)
ALGO_ORDER = ["CSAC-LB", "SAC-Lag", "CPO", "CUP", "FOCOPS"]

RBC_VIOL = 0.516   # Cooling RBC violation rate (deterministic baseline)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def load_summary() -> dict:
    with open(SUMMARY_JSON) as f:
        return json.load(f)

def save(fig, stem: str) -> None:
    for ext in ("pdf", "png"):
        fig.savefig(FIG_DIR / f"{stem}.{ext}")
    plt.close(fig)
    print(f"  -> {stem}.pdf/.png")


# ===========================================================================
# Figure 1 — Mean±Std Violation Rate, All Algorithms (horizontal bar)
# ===========================================================================
def fig_multiseed_viol(summary: dict) -> None:
    algos = [a for a in ALGO_ORDER if a in summary]
    means  = [summary[a]["violation_rate_mean"] * 100 for a in algos]
    stds   = [summary[a]["violation_rate_std"]  * 100 for a in algos]
    seeds  = [summary[a]["n_seeds"] for a in algos]
    colors = [ALGO_COLORS[a] for a in algos]

    fig, ax = plt.subplots(figsize=(COL1, 2.5))

    # Horizontal bars
    y = np.arange(len(algos))
    bars = ax.barh(y, means, xerr=stds, color=colors,
                   error_kw=dict(elinewidth=0.8, capsize=2.5, capthick=0.8,
                                 ecolor="#333333"),
                   height=0.55, zorder=3)

    # RBC dashed line
    ax.axvline(RBC_VIOL * 100, color="#424242", linewidth=0.9,
               linestyle="--", zorder=2, label=f"Cooling RBC ({RBC_VIOL*100:.1f}%)")

    # Annotations: mean% (n=k)
    for i, (m, s, n) in enumerate(zip(means, stds, seeds)):
        label = f"{m:.1f}% (n={n})"
        ax.text(m + s + 0.5, i, label, va="center", ha="left",
                fontsize=5.5, color="#333333")

    ax.set_yticks(y)
    ax.set_yticklabels([f"{a}" for a in algos])
    ax.set_xlabel("Comfort Violation Rate (%)")
    ax.set_title("Multi-Seed Violation Rate: Mean ± Std (Best Checkpoint)")
    ax.set_xlim(0, 115)
    ax.invert_yaxis()
    ax.legend(loc="lower right", fontsize=6)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    save(fig, "fig_multiseed_all_algos_viol")


# ===========================================================================
# Figure 2 — Mean±Std Reward, All Algorithms (horizontal bar)
# ===========================================================================
def fig_multiseed_reward(summary: dict) -> None:
    algos = [a for a in ALGO_ORDER if a in summary]
    means  = [summary[a]["reward_mean"] for a in algos]
    stds   = [summary[a]["reward_std"]  for a in algos]
    seeds  = [summary[a]["n_seeds"] for a in algos]
    colors = [ALGO_COLORS[a] for a in algos]

    fig, ax = plt.subplots(figsize=(COL1, 2.5))

    y = np.arange(len(algos))
    ax.barh(y, means, xerr=stds, color=colors,
            error_kw=dict(elinewidth=0.8, capsize=2.5, capthick=0.8,
                          ecolor="#333333"),
            height=0.55, zorder=3)

    for i, (m, s, n) in enumerate(zip(means, stds, seeds)):
        ax.text(m + s + 10, i, f"{m:.0f} (n={n})",
                va="center", ha="left", fontsize=5.5, color="#333333")

    ax.set_yticks(y)
    ax.set_yticklabels(algos)
    ax.set_xlabel("Total Episode Reward")
    ax.set_title("Multi-Seed Reward: Mean ± Std (Best Checkpoint)")
    ax.invert_yaxis()
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    save(fig, "fig_multiseed_all_algos_reward")


# ===========================================================================
# Figure 3 — Reward vs Violation Scatter, All Seeds
# ===========================================================================
def fig_reward_vs_viol(summary: dict) -> None:
    fig, ax = plt.subplots(figsize=(COL1, 2.8))

    for algo in ALGO_ORDER:
        if algo not in summary:
            continue
        color  = ALGO_COLORS[algo]
        marker = ALGO_MARKERS[algo]
        seeds  = summary[algo]["per_seed"]

        rewards = [s["reward"] for s in seeds]
        viols   = [s["violation_rate"] * 100 for s in seeds]

        ax.scatter(viols, rewards, color=color, marker=marker,
                   s=22, zorder=4, alpha=0.85, label=algo)
        # Mean marker (larger, filled, with black edge)
        ax.scatter(summary[algo]["violation_rate_mean"] * 100,
                   summary[algo]["reward_mean"],
                   color=color, marker=marker, s=60,
                   edgecolors="black", linewidths=0.6,
                   zorder=5)

    # RBC vertical line
    ax.axvline(RBC_VIOL * 100, color="#424242", linewidth=0.9,
               linestyle="--", zorder=2, label=f"RBC ({RBC_VIOL*100:.0f}%)")

    ax.set_xlabel("Comfort Violation Rate (%)")
    ax.set_ylabel("Total Episode Reward")
    ax.set_title("Reward vs. Violation Rate\n(each point = one seed; large = mean)")
    ax.legend(fontsize=6, ncol=1, loc="upper left")
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    save(fig, "fig_multiseed_reward_vs_viol")


# ===========================================================================
# Figure 4 — Cost vs Violation Scatter, All Seeds
# ===========================================================================
def fig_cost_vs_viol(summary: dict) -> None:
    fig, ax = plt.subplots(figsize=(COL1, 2.8))

    for algo in ALGO_ORDER:
        if algo not in summary:
            continue
        color  = ALGO_COLORS[algo]
        marker = ALGO_MARKERS[algo]
        seeds  = summary[algo]["per_seed"]

        costs = [s["cost"] for s in seeds]
        viols = [s["violation_rate"] * 100 for s in seeds]

        ax.scatter(viols, costs, color=color, marker=marker,
                   s=22, zorder=4, alpha=0.85, label=algo)
        ax.scatter(summary[algo]["violation_rate_mean"] * 100,
                   summary[algo]["cost_mean"],
                   color=color, marker=marker, s=60,
                   edgecolors="black", linewidths=0.6, zorder=5)

    ax.axvline(RBC_VIOL * 100, color="#424242", linewidth=0.9,
               linestyle="--", zorder=2, label=f"RBC ({RBC_VIOL*100:.0f}%)")

    ax.set_xlabel("Comfort Violation Rate (%)")
    ax.set_ylabel("Total Constraint Cost")
    ax.set_title("Constraint Cost vs. Violation Rate\n(each point = one seed; large = mean)")
    ax.legend(fontsize=6, ncol=1)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    save(fig, "fig_multiseed_cost_vs_viol")


# ===========================================================================
# Figure 5 — Per-Seed Dot Plot (violation rate), All Algorithms
# ===========================================================================
def fig_seed_dots(summary: dict) -> None:
    """
    Dot plot showing each seed's violation rate alongside the mean (diamond).
    Arranged as a grouped horizontal strip chart, one row per algorithm.
    """
    algos = [a for a in ALGO_ORDER if a in summary]

    fig, ax = plt.subplots(figsize=(COL2, 2.2))

    y_pos   = {a: i for i, a in enumerate(reversed(algos))}
    jitter  = np.random.default_rng(42)

    for algo in algos:
        yc     = y_pos[algo]
        color  = ALGO_COLORS[algo]
        seeds  = summary[algo]["per_seed"]
        viols  = [s["violation_rate"] * 100 for s in seeds]
        j      = jitter.uniform(-0.12, 0.12, size=len(viols))

        # Individual seeds
        ax.scatter(viols, np.full(len(viols), yc) + j,
                   color=color, s=18, alpha=0.75, zorder=4,
                   marker=ALGO_MARKERS[algo])
        # Mean diamond
        mu = summary[algo]["violation_rate_mean"] * 100
        ax.scatter([mu], [yc], color=color, marker="D",
                   s=45, zorder=5, edgecolors="black", linewidths=0.7)
        # Std whisker
        sd = summary[algo]["violation_rate_std"] * 100
        ax.plot([mu - sd, mu + sd], [yc, yc],
                color=color, linewidth=1.2, solid_capstyle="round", zorder=3)

    # RBC line
    ax.axvline(RBC_VIOL * 100, color="#424242", linewidth=0.9,
               linestyle="--", zorder=2)
    ax.text(RBC_VIOL * 100 + 0.4, len(algos) - 0.5,
            f"RBC\n{RBC_VIOL*100:.1f}%", fontsize=6,
            va="top", color="#424242")

    ax.set_yticks(list(y_pos.values()))
    ax.set_yticklabels(list(reversed(algos)))
    ax.set_xlabel("Comfort Violation Rate (%, best checkpoint)")
    ax.set_title("Per-Seed Violation Rates  ◆ = Mean  — = ±1 Std")
    ax.set_xlim(-2, 115)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    # Legend for markers
    handles = [
        mpatches.Patch(color=ALGO_COLORS[a], label=f"{a} (n={summary[a]['n_seeds']})")
        for a in algos if a in summary
    ]
    ax.legend(handles=handles, fontsize=6, ncol=3,
              loc="lower right", framealpha=0.9)

    save(fig, "fig_multiseed_seed_dots")


# ===========================================================================
# Figure 6 — Summary Table Figure (2-panel: viol + reward side by side)
# ===========================================================================
def fig_summary_two_panel(summary: dict) -> None:
    algos  = [a for a in ALGO_ORDER if a in summary]
    means_v = [summary[a]["violation_rate_mean"] * 100 for a in algos]
    stds_v  = [summary[a]["violation_rate_std"]  * 100 for a in algos]
    means_r = [summary[a]["reward_mean"] for a in algos]
    stds_r  = [summary[a]["reward_std"]  for a in algos]
    seeds   = [summary[a]["n_seeds"] for a in algos]
    colors  = [ALGO_COLORS[a] for a in algos]

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(COL2, 2.5))

    y = np.arange(len(algos))
    labels = [f"{a} (n={n})" for a, n in zip(algos, seeds)]

    # — Left: Violation Rate —
    ax1.barh(y, means_v, xerr=stds_v, color=colors, height=0.55, zorder=3,
             error_kw=dict(elinewidth=0.8, capsize=2.5, capthick=0.8,
                           ecolor="#333333"))
    ax1.axvline(RBC_VIOL * 100, color="#424242", linewidth=0.9,
                linestyle="--", zorder=2)
    ax1.text(RBC_VIOL * 100 + 0.5, len(algos) - 0.45,
             f"RBC {RBC_VIOL*100:.0f}%", fontsize=5.5, color="#424242")
    for i, (m, s) in enumerate(zip(means_v, stds_v)):
        ax1.text(m + s + 0.5, i, f"{m:.1f}%", va="center",
                 ha="left", fontsize=5.5, color="#333333")
    ax1.set_yticks(y)
    ax1.set_yticklabels(labels)
    ax1.set_xlabel("Violation Rate (%)")
    ax1.set_title("(a) Safety: Violation Rate")
    ax1.set_xlim(0, 120)
    ax1.invert_yaxis()
    ax1.spines["top"].set_visible(False)
    ax1.spines["right"].set_visible(False)

    # — Right: Reward —
    ax2.barh(y, means_r, xerr=stds_r, color=colors, height=0.55, zorder=3,
             error_kw=dict(elinewidth=0.8, capsize=2.5, capthick=0.8,
                           ecolor="#333333"))
    for i, (m, s) in enumerate(zip(means_r, stds_r)):
        ax2.text(max(m + s + 10, 10), i, f"{m:.0f}",
                 va="center", ha="left", fontsize=5.5, color="#333333")
    ax2.set_yticks(y)
    ax2.set_yticklabels([])
    ax2.set_xlabel("Total Episode Reward")
    ax2.set_title("(b) Efficiency: Episode Reward")
    ax2.invert_yaxis()
    ax2.spines["top"].set_visible(False)
    ax2.spines["right"].set_visible(False)

    fig.suptitle(
        "Multi-Seed Evaluation Summary: Mean ± Std over Best Checkpoints",
        fontsize=8.5, y=1.01
    )
    fig.tight_layout(w_pad=1.5)
    save(fig, "fig_multiseed_summary_two_panel")


# ===========================================================================
# Figure 7 — CSAC-LB 6-Seed Detailed Breakdown
# ===========================================================================
def fig_csaclb_six_seeds(summary: dict) -> None:
    if "CSAC-LB" not in summary:
        return

    data   = summary["CSAC-LB"]["per_seed"]
    seeds  = [int(d["seed"]) for d in data]
    viols  = [d["violation_rate"] * 100 for d in data]
    costs  = [d["cost"] for d in data]
    rewards= [d["reward"] for d in data]

    fig, axes = plt.subplots(1, 3, figsize=(COL2, 2.0))
    color = ALGO_COLORS["CSAC-LB"]

    metrics = [
        (viols,   "Violation Rate (%)", "(a)"),
        (costs,   "Total Cost",         "(b)"),
        (rewards, "Total Reward",       "(c)"),
    ]

    for ax, (vals, ylabel, title) in zip(axes, metrics):
        ax.bar(range(len(seeds)), vals, color=color, width=0.55,
               edgecolor="white", linewidth=0.4, zorder=3)
        mu = np.mean(vals)
        ax.axhline(mu, color="#555", linewidth=0.8, linestyle="--",
                   label=f"Mean={mu:.1f}")
        ax.set_xticks(range(len(seeds)))
        ax.set_xticklabels([f"s{s}" for s in seeds], fontsize=6.5)
        ax.set_ylabel(ylabel, fontsize=7)
        ax.set_title(title, fontsize=8)
        ax.legend(fontsize=5.5, loc="upper right")
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)

        # Annotate bar tops
        for i, v in enumerate(vals):
            ax.text(i, v + 0.01 * max(vals), f"{v:.1f}",
                    ha="center", va="bottom", fontsize=5.5)

    fig.suptitle("CSAC-LB: Results Across 6 Random Seeds", fontsize=9)
    fig.tight_layout()
    save(fig, "fig_csaclb_six_seeds")


# ===========================================================================
# Main
# ===========================================================================
if __name__ == "__main__":
    print("Loading multi-seed summary ...")
    summary = load_summary()
    print(f"  Algorithms: {list(summary.keys())}")
    for algo, d in summary.items():
        print(f"  {algo:10s}  n={d['n_seeds']}  "
              f"viol={d['violation_rate_mean']*100:.1f}%±{d['violation_rate_std']*100:.1f}%  "
              f"rew={d['reward_mean']:.0f}±{d['reward_std']:.0f}")

    print("\nGenerating figures ...")
    fig_multiseed_viol(summary)
    fig_multiseed_reward(summary)
    fig_reward_vs_viol(summary)
    fig_cost_vs_viol(summary)
    fig_seed_dots(summary)
    fig_summary_two_panel(summary)
    fig_csaclb_six_seeds(summary)

    print("\nAll done. Figures saved to:", FIG_DIR)
