#!/bin/bash
# Source this before training: source set_env_v2.sh
export CITYLEARN_STEMS_SOC_LOW=0.0
export CITYLEARN_STEMS_SOC_HIGH=0.95
export CITYLEARN_STEMS_P_BUILDING_MAX=2.273834
export CITYLEARN_STEMS_P_GRID_MAX=27.127751
export CITYLEARN_EV_MISSING_ACTION_MODE=assume_full
export CITYLEARN_SCHEMA=data/citylearn_challenge_2022_phase_all_plus_evs/schema.json
export CITYLEARN_EV_DENSE_COST_SCALE=1.0
export CITYLEARN_REWARD_TYPE=stems
export CITYLEARN_EXPORT_FACTOR=1.0
export CITYLEARN_REWARD_SCALE=1.0
export CITYLEARN_EV_COST_SCALE=1.0
export CITYLEARN_STEMS_BATTERY_COST_SCALE=50.0
export CITYLEARN_STEMS_BUILDING_COST_SCALE=1.0
export CITYLEARN_STEMS_GRID_COST_SCALE=1.0
# STEMS reward weights
export STEMS_MU_ECONOMIC=0.3
export STEMS_ALPHA_GRID=3.0
export STEMS_ALPHA_BUILD=2.0
export STEMS_BETA_RAMP=0.5
export STEMS_XI_RENEWABLE=0.2
export STEMS_LAMBDA_EV=5.0
# CMDP cost weights
export COST_W_C1=10.0
export COST_W_C1_DENSE=5.0
export COST_W_C2=1.0
export COST_W_C3=0.1
export COST_W_C4=5.0
echo "[set_env_v2] All environment variables set ✓"
export CITYLEARN_USE_SHIELD=1
export SHIELD_ENABLE_C3=1
export SHIELD_ENABLE_C4=1
export SHIELD_PENALTY_WEIGHT=5.0
export SHIELD_VERBOSE=1
export CITYLEARN_COST_MODE=hinge
export CITYLEARN_STEMS_PNORM_P=4.0
